apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bot-registry-deployment
  namespace: bot
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bot-registry
    spec:
      containers:
      - name: bot-registry
        imagePullPolicy: Always
        image: ksunhokim/bot-registry
        ports:
        - containerPort: 8080
