apiVersion: v1
kind: ServiceAccount
metadata:
  name: bot-registry
  namespace: bot
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bot-registry-role
rules:
  -
    apiGroups:
    - ""
    - apps
    - autoscaling
    - batch
    - extensions
    - policy
    - rbac.authorization.k8s.io
    resources:
    - deployments
    - pods
    - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bot-registry-rolebinding
subjects:
- kind: ServiceAccount
  name: bot-registry
  namespace: bot
roleRef:
  kind: ClusterRole
  name: bot-registry-role
  apiGroup: rbac.authorization.k8s.io
